accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('register', views.registerPage, name="register"),
	path('login', views.loginPage, name="login"),
	path('logout', views.logoutUser, name="logout"),

    path('user/<slug:slug>', views.userPage, name="userPage"),
    path('account', views.accountSettings, name="accountSettings"),

    path('follow/<slug:slug>', views.follow, name="follow"),#http://localhost:8000/accounts/user/2/follow
]

tweetMe/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweets.urls' , namespace='home')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
    path('tags/', include('hashtag.urls' , namespace='tags')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweets/urls.py
from django.urls import path
from . import views

app_name='tweets'
urlpatterns = [
    path('tweet/<str:pk>/retweet', views.retweetView, name="retweet"),
    path('tweet/<str:pk>/liked', views.likeView, name="liked"),

    path('', views.tweetList, name="tweetList"),
    path('tweet/<str:pk>', views.tweetDetail, name="tweetDetail"),
    path('update/<str:pk>', views.tweetUpdate, name="tweetUpdate"),
    path('delete/<str:pk>', views.tweetDelete, name="tweetDelete"),
]

tweets/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Profile
from django.utils import timezone

# Create your models here.
class TweetManager(models.Manager):
	def retweet(self, user, parent_obj):
		if parent_obj.parent:
			og_parent = parent_obj.parent
		else:
			og_parent = parent_obj
		qs = self.get_queryset().filter(
				tweetUser=user,
				parent=og_parent,
				).filter(
					timestamp__year=timezone.now().year,
					timestamp__month=timezone.now().month,
					timestamp__day=timezone.now().day,
				)
		if qs.exists():
			return None
		obj = self.model(
			parent = og_parent,
			tweetUser = user,
			content = parent_obj.content,
		)
		obj.save()
		return obj

	def liked_toggle(self, user, tweet_obj):
		if user in tweet_obj.liked.all():
			liked_value = False
			tweet_obj.liked.remove(user)
		else:
			liked_value = True
			tweet_obj.liked.add(user)
		return liked_value


class Tweets(models.Model):
	parent = models.ForeignKey("self", null=True, blank=True, on_delete= models.SET_NULL)
	tweetUser = models.ForeignKey(Profile, on_delete= models.SET_NULL, null=True)
	liked = models.ManyToManyField(User, blank=True, related_name='liked')
	content = models.CharField(max_length=140)
	updated = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)

	objects = TweetManager()

	def __str__(self):
		return str(self.content)

	class Meta:
		verbose_name = "Tweet"
		verbose_name_plural = "Tweets"

tweets/forms.py
from django import forms
from .models import Tweets

class TweetModelForm(forms.ModelForm):
    content = forms.CharField(label='',
                widget=forms.Textarea(
                        attrs={'placeholder': "Your message",
                            "class": "form-control"}
                    ))
    class Meta:
        model = Tweets
        fields = [
            #"user",
            "content"
        ]
        #exclude = ['user']

    def clean_content(self, *args, **kwargs):
        content = self.cleaned_data.get("content")
        if content == "abc":
            raise forms.ValidationError("Cannot be ABC")
        return content

tweets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from accounts.models import Profile

from django.db.models import Q

from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='accounts:login')
def tweetList(request):
	user_profile, created = Profile.objects.get_or_create(user=request.user) #or user_profile=request.user
	im_following = user_profile.get_following()

	tweets = Tweets.objects.all()
	#q1 = tweets.filter(tweetUser__user__in=im_following)
	#q2 = tweets.filter(tweetUser__user=im_following)
	tweets=(tweets.filter(tweetUser__user__in=im_following) | tweets.filter(tweetUser=user_profile)).distinct().order_by("-timestamp")

	search_query = request.GET.get('q')
	if search_query:
		tweets = tweets.filter(
			Q(profile__user__username__icontains = search_query)|
			Q(content__icontains= search_query)
		).distinct()

	paginator = Paginator(tweets, 2) # Show 2 posts per page

	page = request.GET.get('page')
	tweets = paginator.get_page(page)

	form = TweetModelForm()
	if request.method == 'POST':
		form = TweetModelForm(request.POST)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.tweetUser = request.user.profile
			instance.save()
			return redirect('home:tweetList')

	content = {
		'tweets' : tweets,
		'form' : form,
		'user_profile' : user_profile,
	}
	return render(request, 'tweetList.html', content)

@login_required(login_url='accounts:login')
def tweetDetail(request,pk):
	tweet = Tweets.objects.get(id=pk)
	content = {
		'tweet' : tweet,
	}
	return render(request, 'tweetDetail.html', content)

@login_required(login_url='accounts:login')
def tweetUpdate(request,pk):
	tweet = Tweets.objects.get(id=pk)

	form = TweetModelForm(instance=tweet)
	if request.method == 'POST':
		form = TweetModelForm(request.POST, instance=tweet)
		if form.is_valid():
			form.save()
			return redirect('home:tweetList')

	content = {
		'tweet' : tweet,
		'form': form,
	}
	return render(request, 'tweetUpdate.html', content)

@login_required(login_url='accounts:login')
def tweetDelete(request, pk):
	tweet = Tweets.objects.get(id=pk)
	if request.method == 'POST':
		tweet.delete()
		return redirect('home:tweetList')

	return render(request, 'tweetDelete.html', {'tweet': tweet})

@login_required(login_url='accounts:login')
def retweetView(request, pk):
	tweet = get_object_or_404(Tweets, pk=pk)
	if request.user.is_authenticated:
		newTweet = Tweets.objects.retweet(request.user.profile, tweet)#Tweets.tweetUser must be prifile instinces
	else:
		return redirect('accounts:login')
	return redirect('home:tweetList')


@login_required(login_url='accounts:login')
def likeView(request, pk):
	tweet = get_object_or_404(Tweets, pk=pk)
	if request.user.is_authenticated:
		liked_value = Tweets.objects.liked_toggle(request.user, tweet)
	else:
		return redirect('accounts:login')
	return redirect('home:tweetList')

tweets/templates/tweetDelete.html
{% extends 'base.html' %}
{% block content %}


<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">

			<p>Are you sure you want to delete "{{tweet}}"?</p>
			<form  action="" method="post">
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'home:tweetList' %}">Go back</a>

			  	<input class="btn btn-danger" type="submit"/>
			</form>
		</div>
	</div>
</div>


{% endblock content %}

tweets/templates/tweetDetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include "form.html" with form=form btn_title='Tweet' %}

<div class="media">
<img class="align-self-start mr-3" src="">
<div class="media-body">
  <h5 class="mt-0">{{tweet.user}}</h5>
  <p>{{tweet.content}}</p>
  {{tweet.timestamp}}
  {{tweet.timestamp|timesince}} ago
</div>
</div>

{% endblock content %}

tweets/templates/tweetList.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="post">
  {% csrf_token %}
  {{form}}
  <input class="btn btn-primary" type="submit" name="Tweet" value="Tweet">
</form>
{% for tweet in tweets %}
<div class='row'>
  <div class='col'>
    <div class="media">
    <img class="align-self-start mr-3" src="{% static 'images/deafult.png' %}">
    <div class="media-body">
      <h5 class="mt-0"><a href="{% url 'accounts:userPage' tweet.tweetUser.slug %}">{{tweet.tweetUser}}</a></h5>
      {% if tweet.parent %}
        <hr>
        <p>Retweeted from <a href="{% url 'accounts:userPage' tweet.parent.tweetUser.slug %}">{{tweet.parent.tweetUser}}</a></p>
        <hr>
      {% endif %}
      <p>{{tweet.content}}</p>
      {{tweet.timestamp}}
      {{tweet.timestamp|timesince}} ago <br><br>
      <div class="row">
        <a class="btn btn-success" href="{% url 'home:liked' tweet.id %}" role="button">{% if request.user in tweet.liked.all %}Unlike{% else %}Like{% endif %}({{tweet.liked.count}})</a> &nbsp; &nbsp;
        <a class="btn btn-primary" href="{% url 'home:tweetDetail' tweet.id %}" role="button">Detail</a> &nbsp; &nbsp;
        <a class="btn btn-success" href="{% url 'home:tweetUpdate' tweet.id %}" role="Update">Update</a> &nbsp; &nbsp;
        <a class="btn btn-danger" href="{% url 'home:tweetDelete' tweet.id %}" role="Delete">Delete</a> &nbsp; &nbsp;
        <a class="btn btn-danger" href="{% url 'home:retweet' tweet.id %}" role="Retweet">Retweet</a> &nbsp; &nbsp;
      </div>
    </div>

    </div>
    <br><br>
  <hr>
</div>
</div>
{% empty %}
  <p>Opps! No such keyWord found</p>
{% endfor %}



{% if tweets.has_other_pages %}
<nav aria-label="...">
  <ul class="pagination">

    {% if tweets.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{tweets.previous_page_number}}" tabindex="-1">Previous</a>
      </li>
    {% else %}
      <li class="disabled"></li>
    {% endif %}

    {% for pages in tweets.paginator.page_range %}
      {% if tweets.number == pages %}
        <li class="page-item active"><a class="page-link" href="#">{{pages}}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{pages}}">{{pages}}</a></li>
      {% endif %}
    {% endfor %}

    {% if tweets.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{tweets.next_page_number}}">Next</a>
      </li>
    {% else %}
        <li class="disabled"></li>
    {% endif %}

  </ul>
</nav>
{% endif %}

{% endblock content %}

tweets/templates/tweetUpdate.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include "form.html" with form=form btn_title='Update' %}


{% endblock content %}