accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('register', views.registerPage, name="register"),
	path('login', views.loginPage, name="login"),
	path('logout', views.logoutUser, name="logout"),

    path('user/<slug:slug>', views.userPage, name="userPage"),
    path('account', views.accountSettings, name="accountSettings"),

    path('follow/<slug:slug>', views.follow, name="follow"),#http://localhost:8000/accounts/user/2/follow
]

tweetMe/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweets.urls' , namespace='home')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
    path('tags/', include('hashtag.urls' , namespace='tags')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweets/urls.py
from django.urls import path
from . import views

app_name='tweets'
urlpatterns = [
    path('tweet/<str:pk>/retweet', views.retweetView, name="retweet"),
    path('tweet/<str:pk>/liked', views.likeView, name="liked"),

    path('', views.tweetList, name="tweetList"),
    path('tweet/<str:pk>', views.tweetDetail, name="tweetDetail"),
    path('update/<str:pk>', views.tweetUpdate, name="tweetUpdate"),
    path('delete/<str:pk>', views.tweetDelete, name="tweetDelete"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


# Create your models here.
class UserProfileManager(models.Manager):
	pass


class Profile(models.Model):
	user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, related_name='profile')#with the related_name here we can use userProfile.profile.followed_by.county insted of userProfile.user.followed_by.count
	name = models.CharField(max_length=200, null=True)
	phone = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200, null=True)
	profile_pic = models.ImageField(default="default.png", null=True, blank=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
	following   = models.ManyToManyField(User, blank=True, related_name='followed_by')
	# user.profile.following -- users i follow
	# user.followed_by -- users that follow me -- reverse relationship
	slug = models.SlugField(blank=True, null=True)


	def save(self , *args , **kwargs):
		if not self.slug and self.name :
			self.slug = slugify(self.name)
		super(Profile , self).save(*args , **kwargs)

	objects = UserProfileManager()

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Profile"
		verbose_name_plural = "Profiles"

	def get_following(self):
		users  = self.following.all()
		return users.exclude(username=self.user.username)

	def get_followors(self):
		users  = self.user.followed_by.all()
		return users.exclude(user=self.user)

accounts/forms.py
from django.forms import ModelForm
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']


class UserProfileForm(ModelForm):
	class Meta:
		model = Profile
		fields = '__all__'
		exclude = ['user']

accounts/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse
from .models import *
from .forms import CreateUserForm, UserProfileForm

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
#@login_required(login_url='login')
from .decorators import unauthenticated_user

# Create your views here.
@unauthenticated_user
def registerPage(request):
	form = CreateUserForm()
	if request.method == 'POST':
		form = CreateUserForm(request.POST)

		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, 'Account was created for ' + username)
			return redirect('accounts:login')


	content = {'form':form}
	return render(request, 'register.html', content)

@unauthenticated_user
def loginPage(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password =request.POST.get('password')
		user = authenticate(request, username=username, password=password)

		if user is not None:
			login(request, user)
			return redirect('home:tweetList')
		else:
			messages.info(request, 'Username OR password is incorrect')
	content = {}
	return render(request, 'login.html', content)

@login_required(login_url='accounts:login')
def logoutUser(request):
	logout(request)
	return redirect('accounts:login')

@login_required(login_url='accounts:login')
def userPage(request, slug):
	user_profile = Profile.objects.get(slug=slug)

	tweets = user_profile.tweets_set.all().order_by("-timestamp") #user tweets_set

	#follow check--------------------------------------------------------------
	toggle_user = get_object_or_404(Profile, slug__iexact=slug)
	profile, created = Profile.objects.get_or_create(user=request.user) #or user_profile=request.user
	if toggle_user.user in profile.following.all():
		follow = True
	else:
		follow = False

	content = {
		'user_profile' : user_profile,
		'tweets' : tweets,
		'follow': follow,
	}
	return render(request, 'user.html', content)


@login_required(login_url='accounts:login')
def accountSettings(request):
	profile = request.user.profile
	form = UserProfileForm(instance=profile)

	if request.method == 'POST':
		form = UserProfileForm(request.POST, request.FILES, instance=profile)
		if form.is_valid():
			form.save()


	content = {
		'form':form
		}

	return render(request, 'settings.html', content)



@login_required(login_url='accounts:login')
def follow(request,slug):
	toggle_user = get_object_or_404(Profile, slug__iexact=slug)
	if request.user.is_authenticated:
		user_profile, created = Profile.objects.get_or_create(user=request.user) #or user_profile=request.user
		if toggle_user.user in user_profile.following.all():
			user_profile.following.remove(toggle_user.user)
		else:
			user_profile.following.add(toggle_user.user)


	return redirect('accounts:userPage', slug)

accounts/templates/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2">Sign Up</a>
					</div>
          <div class="d-flex justify-content-center links">
						Forgot password? <a href="#" class="ml-2">Reset password</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

</html>

accounts/templates/register.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>



				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>

					</form>
				</div>

				{{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

accounts/templates/settings.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'home:tweetList' %}"> &#8592; Back to Profile</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
			<img class="profile-pic" src="{{request.user.customer.profile_pic.url}}" >

		</div>
	</div>
	<div class="col-md-9">
		<div class="card card-body">

			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}

			<input class="btn btn-primary" type="submit" name="Update Information">
			</form>
		</div>
	</div>
</div>



{% endblock %}

accounts/templates/user.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
      <a class="btn btn-warning" href="{% url 'home:tweetList' %}"> &#8592; Back to Home</a>
			<hr>
      <a class="btn btn-warning" href="{% url 'accounts:accountSettings' %}"> &#8592; Go to Account Settings</a>
      <hr>
			<h3 style="text-align: center">Profile</h3>
			<hr>
			<img class="profile-pic" src="{{request.user.profile.profile_pic.url}}" >
			<h3>{{user_profile.user.username}}</h3>
			{% if request.user.profile.slug ==  user_profile.slug %}
				<p></p>
			{% else %}
				<a class="btn btn-primary" href="{% url 'accounts:follow' user_profile.slug %}" role="button">{% if follow %}Unfollow{% else %}Follow{% endif %}</a>
			{% endif %}

		</div>
	</div>
	<div class="col-md-9">
		<div class="card card-body">


			<h2>Following({{user_profile.get_following.count}})</h2>
			{% for user in user_profile.get_following %}
			 <a href="{% url 'accounts:userPage' user.profile.slug %}">{{user.username}}</a>
			{% empty %}
				<p>No following</p>
			{% endfor %}

			<h2>Followors({{user_profile.get_followors.count}})</h2>
			{% for profile in user_profile.get_followors %}
			 <a href="{% url 'accounts:userPage' profile.slug %}">{{profile.user.username}}</a>
			{% empty %}
				<p>No Followors</p>
			{% endfor %}


			{% for tweet in tweets %}
			<div class='row'>
			  <div class='col'>
			    <div class="media">
			    <img class="align-self-start mr-3" src="{% static 'images/deafult.png' %}">
			    <div class="media-body">
			      <h5 class="mt-0">{{tweet.tweetUser}}</h5>
			      <p>{{tweet.content}}</p>
			      {{tweet.timestamp}}
			      {{tweet.timestamp|timesince}} ago <br><br>
			      <div class="row">
			        <a class="btn btn-primary" href="{% url 'home:tweetDetail' tweet.id %}" role="button">Detail</a> &nbsp; &nbsp;
			        <a class="btn btn-success" href="{% url 'home:tweetUpdate' tweet.id %}" role="Update">Update</a> &nbsp; &nbsp;
			        <a class="btn btn-danger" href="{% url 'home:tweetDelete' tweet.id %}" role="Delete">Delete</a> &nbsp; &nbsp;
							<a class="btn btn-danger" href="{% url 'home:retweet' tweet.id %}" role="Retweet">Retweet</a> &nbsp; &nbsp;
			      </div>
			    </div>

			    </div>
			    <br><br>
			  <hr>
			</div>
			</div>
			{% empty %}
			  <p>Opps! No such keyWord found</p>
			{% endfor %}

		</div>
	</div>
</div>



{% endblock %}