accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('register', views.registerPage, name="register"),
	path('login', views.loginPage, name="login"),
	path('logout', views.logoutUser, name="logout"),

    path('user/<slug:slug>', views.userPage, name="userPage"),
    path('account', views.accountSettings, name="accountSettings"),

    path('follow/<slug:slug>', views.follow, name="follow"),#http://localhost:8000/accounts/user/2/follow
]

tweetMe/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweets.urls' , namespace='home')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
    path('tags/', include('hashtag.urls' , namespace='tags')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweets/urls.py
from django.urls import path
from . import views

app_name='tweets'
urlpatterns = [
    path('tweet/<str:pk>/retweet', views.retweetView, name="retweet"),
    path('tweet/<str:pk>/liked', views.likeView, name="liked"),

    path('', views.tweetList, name="tweetList"),
    path('tweet/<str:pk>', views.tweetDetail, name="tweetDetail"),
    path('update/<str:pk>', views.tweetUpdate, name="tweetUpdate"),
    path('delete/<str:pk>', views.tweetDelete, name="tweetDelete"),
]

templates/base.html
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>TweetMe</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static '/css/main.css'  %}" rel="stylesheet" type="text/css">
    <script src="https://kit.fontawesome.com/e5f4960269.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/mainJS.js' %}"></script>
  </head>

  <body>

    {% include 'nav.html' %}
    <div class="container">
    {% block content %}


    {% endblock content %}
    </div>
    {% include 'footer.html' %}

  </body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

templates/footer.html
<footer class="footer">
     <div class="container">
       <span class="text-muted">Copyright @ our footer</span>
     </div>
   </footer>

templates/form.html
<form class='form' method='POST' action="">
   {% csrf_token %}
    {{ form.as_p }}
    <input class='btn btn-primary' type="submit" value="{{ btn_title }}" />
</form>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:tweetList' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:userPage' request.user.profile.slug %}">Profile</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search Tweets" name='q' value="{{request.Get.q}}" aria-label="Search">
      <input class="btn btn-outline-success my-2 my-sm-0" type="submit" name="Search" value="Search">
    </form>
  </div>
</nav>